version: 0.0
os: linux
runas: root

files:
  - source: /
    destination: /home/ubuntu/abhay-practice-node-express-realworld-example-app/
    overwrite: true
    timeout: 50

hooks:
  BeforeInstall:
    - location: script/install.sh
      timeout: 50
      runas: root
  ApplicationStop:
    - location: script/stop.sh
      timeout: 50
      runas: root
  ApplicationStart:
    - location: script/start.sh
      timeout: 60
      runas: root
 
