version: 0.0
os: linux
runas: root

files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app
    overwrite: true
    timeout: 50

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 50
      runas: root
  ApplicationStop:
    - location: scripts/stop_script.sh
      timeout: 50
      runas: root
  ApplicationStart:
    - location: scripts/start_script.sh
      timeout: 60
      runas: root
 
