version: 0.2
runas: root
env:
  secrets-manager:
    MONGODB_URL: "ABHAY_MONGO_SECRET:mongodb_url"
    
phases: 
  pre_build:
    commands: 
      - echo Build started on `date`
      - echo "MONGODB_URL_ABHAY=$MONGODB_URL" > .env
      
  build:
    commands: 
      - npm install
      - npm install --save dotenv
      
  post_build:
    commands: 
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
